=== TermCOMP/TPDB/xml/xtc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: xtc.xsd,v 1.1 2009/04/15 12:13:51 rene Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="0.4">
  <xs:element name="problem">
    <xs:annotation>
      <xs:documentation>This is the root element representing a termination problem.</xs:documentation>
      <xs:documentation>Versioning Information:</xs:documentation>
      <xs:documentation>Version 0.4: added higher-order features (courtesy Albert Rubio and Rene Thiemann)</xs:documentation>
      <xs:documentation>Version 0.32: removed the targetNamespace</xs:documentation>
      <xs:documentation>Version 0.31: adds the capability to have multiple originalfilename tags;
      removed the strategy=NONE.</xs:documentation>
      <xs:documentation>Version 0.3: adds the /problem/metainformation/originalfilename tag.</xs:documentation>
      <xs:documentation>Version 0.2: first official release</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="trs"/>
        <xs:element ref="strategy"/>
        <xs:element ref="startterm" minOccurs="0"/>
        <xs:element ref="status" minOccurs="0"/>
        <xs:element ref="metainformation" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="termination"/>
            <xs:enumeration value="complexity"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="trs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="rules"/>
        <xs:choice>
          <xs:element ref="signature"/>
          <xs:element ref="higherOrderSignature"/>
        </xs:choice>
        <xs:element ref="comment" minOccurs="0"/>
        <xs:element ref="conditiontype" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
        <xs:element ref="relrules" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="relrules">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="rule"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="signature">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="funcsym"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="funcsym">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="arity"/>
        <xs:element ref="theory" minOccurs="0"/>
        <xs:element ref="replacementmap" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="arity" type="xs:int"/>

  <xs:element name="theory">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="A"/>
        <xs:enumeration value="C"/>
        <xs:enumeration value="AC"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="conditiontype">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="JOIN"/>
        <xs:enumeration value="ORIENTED"/>
        <xs:enumeration value="OTHER"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="strategy">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="FULL"/>
        <xs:enumeration value="INNERMOST"/>
        <xs:enumeration value="OUTERMOST"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="status">
    <xs:annotation>
      <xs:documentation>
       This tag shows the termination status of this problem, if known.
       The reason for using sub-elements is that &lt;yes/&gt; can optionally 
       be extended by complexity bound information.
     </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:choice>
        <xs:element ref="no"/>
        <xs:element ref="maybe"/>
        <xs:element ref="yes"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="metainformation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="originalfilename" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="author" minOccurs="0"/>
        <xs:element ref="date" minOccurs="0"/>
        <xs:element ref="comment" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="originalfilename" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>

  <xs:element name="date" type="xs:date"/>
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lhs"/>
        <xs:element ref="rhs"/>
        <xs:element minOccurs="0" ref="conditions"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="conditions">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="condition"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lhs"/>
        <xs:element ref="rhs"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>

  <xs:element name="comment">
    <xs:complexType mixed="true">
      <xs:attribute name="author" use="required" type="xs:string"/>
      <xs:attribute name="date" use="required" type="xs:date"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="lhs">
    <xs:complexType>
      <xs:group ref="term"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="rhs">
    <xs:complexType>
      <xs:group ref="term"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="higherOrderSignature">
    <xs:annotation>
      <xs:documentation/>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="variableTypeInfo" minOccurs="0">
          <xs:annotation>
            <xs:documentation>type for free variables
</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="varDeclaration" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="functionSymbolTypeInfo">
          <xs:annotation>
            <xs:documentation>a higher-order symbol f with children types t1,...,tn,t has type: (t1,...,tn) -&gt; t</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="funcDeclaration" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="varDeclaration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="var"/>
        <xs:element ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="funcDeclaration">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="typeDeclaration"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="typeDeclaration">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="type">
    <xs:complexType>
      <xs:choice>
        <xs:element name="basic" type="xs:string"/>
        <xs:element name="arrow">
          <xs:annotation>
            <xs:documentation/>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="type"/>
              <xs:element ref="type"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:group name="term">
    <xs:annotation>
      <xs:documentation>for first-order terms, only funapp and var may be used</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:element name="funapp">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="name" maxOccurs="1"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="arg">
              <xs:complexType>
                <xs:group ref="term"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element ref="var"/>
      <xs:element name="lambda">
        <xs:annotation>
          <xs:documentation>the type is the type of the bound variable</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="var"/>
            <xs:element ref="type"/>
            <xs:group ref="term"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="application">
        <xs:annotation>
          <xs:documentation>an application of a function (first term) on an argument (second term): (first second)</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:group ref="term"/>
            <xs:group ref="term"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:choice>
  </xs:group>
  <xs:element name="var" type="xs:string"/>
  <xs:element name="replacementmap">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entry" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="entry" type="xs:int"/>

  <xs:element name="startterm">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="constructor-based"/>
        <xs:element ref="full"/>
        <xs:element ref="automaton"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="constructor-based">
    <xs:complexType/>
  </xs:element>

  <xs:element name="full">
    <xs:complexType/>
  </xs:element>

  <xs:element name="automaton">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="automatonstuff"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="automatonstuff" type="xs:string"/>

  <xs:element name="no">
    <xs:complexType/>
  </xs:element>

  <xs:element name="maybe">
    <xs:complexType/>
  </xs:element>

  <xs:element name="yes">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element name="lowerbound" type="bound"/>
        <xs:element name="upperbound" type="bound"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="bound">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="?"/>
          <xs:enumeration value="POLY"/>
          <xs:enumeration value="O(1)"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="O\(n\^[0-9]+\)"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
</xs:schema>

=== TermCOMP/TPDB/Higher_Order_Rewriting_Union_Beta/Mixed_HO_10/if.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../xml/xtcHTML.xsl"?>
<problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xml/xtc.xsd" type="termination">
<trs>
<rules>
<rule>
<lhs>
<funapp>
<name>if</name>
<arg>
<funapp>
<name>true</name>
</funapp>
</arg>
<arg>
<var>X</var>
</arg>
<arg>
<var>Y</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>X</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>if</name>
<arg>
<funapp>
<name>false</name>
</funapp>
</arg>
<arg>
<var>X</var>
</arg>
<arg>
<var>Y</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>Y</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>h</name>
<arg>
<var>F</var>
</arg>
<arg>
<var>G</var>
</arg>
<arg>
<funapp>
<name>0</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>0</name>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>h</name>
<arg>
<var>F</var>
</arg>
<arg>
<var>G</var>
</arg>
<arg>
<funapp>
<name>s</name>
<arg>
<var>Y</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<application>
<var>G</var>
<funapp>
<name>h</name>
<arg>
<var>F</var>
</arg>
<arg>
<var>G</var>
</arg>
<arg>
<funapp>
<name>if</name>
<arg>
<application>
<var>F</var>
<var>Y</var>
</application>
</arg>
<arg>
<var>Y</var>
</arg>
<arg>
<funapp>
<name>0</name>
</funapp>
</arg>
</funapp>
</arg>
</funapp>
</application>
</rhs>
</rule>
</rules>
<higherOrderSignature>
<variableTypeInfo>
<varDeclaration>
<var>X</var>
<type>
<basic>nat</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>Y</var>
<type>
<basic>nat</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>F</var>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>bool</basic>
</type>
</arrow>
</type>
</varDeclaration>
<varDeclaration>
<var>G</var>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</arrow>
</type>
</varDeclaration>
</variableTypeInfo>
<functionSymbolTypeInfo>
<funcDeclaration>
<name>0</name>
<typeDeclaration>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>h</name>
<typeDeclaration>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>bool</basic>
</type>
</arrow>
</type>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</arrow>
</type>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>if</name>
<typeDeclaration>
<type>
<basic>bool</basic>
</type>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>true</name>
<typeDeclaration>
<type>
<basic>bool</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>false</name>
<typeDeclaration>
<type>
<basic>bool</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>s</name>
<typeDeclaration>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
</functionSymbolTypeInfo>
</higherOrderSignature>
</trs>
<strategy>FULL</strategy>
<metainformation>
<originalfilename>.</originalfilename>
</metainformation>
</problem>

=== TermCOMP/TPDB/Higher_Order_Rewriting_Union_Beta/Mixed_HO_10/from.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../xml/xtcHTML.xsl"?>
<problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xml/xtc.xsd" type="termination">
<trs>
<rules>
<rule>
<lhs>
<funapp>
<name>if</name>
<arg>
<funapp>
<name>true</name>
</funapp>
</arg>
<arg>
<var>X</var>
</arg>
<arg>
<var>Y</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>X</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>if</name>
<arg>
<funapp>
<name>false</name>
</funapp>
</arg>
<arg>
<var>X</var>
</arg>
<arg>
<var>Y</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>Y</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>lteq</name>
<arg>
<funapp>
<name>s</name>
<arg>
<var>M</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>o</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>false</name>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>lteq</name>
<arg>
<funapp>
<name>o</name>
</funapp>
</arg>
<arg>
<var>M</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>true</name>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>lteq</name>
<arg>
<funapp>
<name>s</name>
<arg>
<var>M</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>s</name>
<arg>
<var>K</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>lteq</name>
<arg>
<var>M</var>
</arg>
<arg>
<var>K</var>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>from</name>
<arg>
<var>M</var>
</arg>
<arg>
<funapp>
<name>nil</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>nil</name>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>from</name>
<arg>
<var>M</var>
</arg>
<arg>
<funapp>
<name>cons</name>
<arg>
<var>H</var>
</arg>
<arg>
<var>Z</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>if</name>
<arg>
<funapp>
<name>lteq</name>
<arg>
<var>M</var>
</arg>
<arg>
<var>H</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>cons</name>
<arg>
<var>H</var>
</arg>
<arg>
<var>Z</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>from</name>
<arg>
<var>M</var>
</arg>
<arg>
<var>Z</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>chain</name>
<arg>
<var>F</var>
</arg>
<arg>
<funapp>
<name>nil</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>nil</name>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>chain</name>
<arg>
<var>F</var>
</arg>
<arg>
<funapp>
<name>cons</name>
<arg>
<var>H</var>
</arg>
<arg>
<var>Z</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>cons</name>
<arg>
<application>
<var>F</var>
<var>H</var>
</application>
</arg>
<arg>
<funapp>
<name>chain</name>
<arg>
<var>F</var>
</arg>
<arg>
<funapp>
<name>from</name>
<arg>
<application>
<var>F</var>
<var>H</var>
</application>
</arg>
<arg>
<var>Z</var>
</arg>
</funapp>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>incch</name>
<arg>
<var>X</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>chain</name>
<arg>
<lambda>
<var>x</var>
<type>
<basic>N</basic>
</type>
<funapp>
<name>s</name>
<arg>
<var>x</var>
</arg>
</funapp>
</lambda>
</arg>
<arg>
<var>X</var>
</arg>
</funapp>
</rhs>
</rule>
</rules>
<higherOrderSignature>
<variableTypeInfo>
<varDeclaration>
<var>X</var>
<type>
<basic>list</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>Y</var>
<type>
<basic>list</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>Z</var>
<type>
<basic>list</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>M</var>
<type>
<basic>N</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>K</var>
<type>
<basic>N</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>H</var>
<type>
<basic>N</basic>
</type>
</varDeclaration>
<varDeclaration>
<var>F</var>
<type>
<arrow>
<type>
<basic>N</basic>
</type>
<type>
<basic>N</basic>
</type>
</arrow>
</type>
</varDeclaration>
</variableTypeInfo>
<functionSymbolTypeInfo>
<funcDeclaration>
<name>o</name>
<typeDeclaration>
<type>
<basic>N</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>s</name>
<typeDeclaration>
<type>
<basic>N</basic>
</type>
<type>
<basic>N</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>true</name>
<typeDeclaration>
<type>
<basic>B</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>false</name>
<typeDeclaration>
<type>
<basic>B</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>nil</name>
<typeDeclaration>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>cons</name>
<typeDeclaration>
<type>
<basic>N</basic>
</type>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>if</name>
<typeDeclaration>
<type>
<basic>B</basic>
</type>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>lteq</name>
<typeDeclaration>
<type>
<basic>N</basic>
</type>
<type>
<basic>N</basic>
</type>
<type>
<basic>B</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>from</name>
<typeDeclaration>
<type>
<basic>N</basic>
</type>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>chain</name>
<typeDeclaration>
<type>
<arrow>
<type>
<basic>N</basic>
</type>
<type>
<basic>N</basic>
</type>
</arrow>
</type>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>incch</name>
<typeDeclaration>
<type>
<basic>list</basic>
</type>
<type>
<basic>list</basic>
</type>
</typeDeclaration>
</funcDeclaration>
</functionSymbolTypeInfo>
</higherOrderSignature>
</trs>
<strategy>FULL</strategy>
<metainformation>
<originalfilename>.</originalfilename>
</metainformation>
</problem>

=== TermCOMP/TPDB/Higher_Order_Rewriting_Union_Beta/Mixed_HO_10/counterex2.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../xml/xtcHTML.xsl"?>
<problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xml/xtc.xsd" type="termination">
<trs>
<rules>
<rule>
<lhs>
<funapp>
<name>f</name>
<arg>
<funapp>
<name>g</name>
<arg>
<var>X</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>g</name>
<arg>
<var>X</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<application>
<var>X</var>
<funapp>
<name>g</name>
<arg>
<var>X</var>
</arg>
</funapp>
</application>
</rhs>
</rule>
</rules>
<higherOrderSignature>
<variableTypeInfo>
<varDeclaration>
<var>X</var>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</arrow>
</type>
</varDeclaration>
</variableTypeInfo>
<functionSymbolTypeInfo>
<funcDeclaration>
<name>f</name>
<typeDeclaration>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
<funcDeclaration>
<name>g</name>
<typeDeclaration>
<type>
<arrow>
<type>
<basic>nat</basic>
</type>
<type>
<basic>nat</basic>
</type>
</arrow>
</type>
<type>
<basic>nat</basic>
</type>
</typeDeclaration>
</funcDeclaration>
</functionSymbolTypeInfo>
</higherOrderSignature>
</trs>
<strategy>FULL</strategy>
<metainformation>
<originalfilename>.</originalfilename>
</metainformation>
</problem>

=== TermCOMP/TPDB/TRS_Conditional/COPS/310.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../xml/xtcHTML.xsl"?>
<problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" type="termination" xsi:noNamespaceSchemaLocation="../../xml/xtc.xsd">
<trs>
<rules>
<rule>
<lhs>
<funapp>
<name>gcd</name>
<arg>
<funapp>
<name>add</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>gcd</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>gcd</name>
<arg>
<var>y</var>
</arg>
<arg>
<funapp>
<name>add</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>gcd</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>gcd</name>
<arg>
<var>x</var>
</arg>
<arg>
<funapp>
<name>0</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<var>x</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>gcd</name>
<arg>
<funapp>
<name>0</name>
</funapp>
</arg>
<arg>
<var>x</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>x</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>add</name>
<arg>
<funapp>
<name>0</name>
</funapp>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>y</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>add</name>
<arg>
<funapp>
<name>s</name>
<arg>
<var>x</var>
</arg>
</funapp>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>s</name>
<arg>
<funapp>
<name>add</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>gcd</name>
<arg>
<var>x</var>
</arg>
<arg>
<var>y</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>gcd</name>
<arg>
<var>y</var>
</arg>
<arg>
<var>x</var>
</arg>
</funapp>
</rhs>
<conditions>
<condition>
<lhs>
<funapp>
<name>leq</name>
<arg>
<var>y</var>
</arg>
<arg>
<var>x</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>false</name>
</funapp>
</rhs>
</condition>
</conditions>
</rule>
</rules>
<signature>
<funcsym>
<name>gcd</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>add</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>0</name>
<arity>0</arity>
</funcsym>
<funcsym>
<name>s</name>
<arity>1</arity>
</funcsym>
<funcsym>
<name>leq</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>false</name>
<arity>0</arity>
</funcsym>
</signature>
<conditiontype>ORIENTED</conditiontype>
</trs>
<strategy>FULL</strategy>
</problem>

=== TermCOMP/TPDB/Runtime_Complexity_Innermost_Rewriting2/Secret_05_TRS/cime2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../xml/xtcHTML.xsl"?>
<problem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xml/xtc.xsd" type="complexity">
<trs>
<rules>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<var>a</var>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>msubst</name>
<arg>
<var>a</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>cons</name>
<arg>
<var>a</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>cons</name>
<arg>
<var>a</var>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
<arg>
<var>u</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>t</var>
</arg>
<arg>
<var>u</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<funapp>
<name>id</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<var>s</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>id</name>
</funapp>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</lhs>
<rhs>
<var>s</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
<arg>
<var>u</var>
</arg>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>circ</name>
<arg>
<funapp>
<name>cons</name>
<arg>
<funapp>
<name>lift</name>
</funapp>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</arg>
<arg>
<var>u</var>
</arg>
</funapp>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>subst</name>
<arg>
<var>a</var>
</arg>
<arg>
<funapp>
<name>id</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<var>a</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>msubst</name>
<arg>
<var>a</var>
</arg>
<arg>
<funapp>
<name>id</name>
</funapp>
</arg>
</funapp>
</lhs>
<rhs>
<var>a</var>
</rhs>
</rule>
<rule>
<lhs>
<funapp>
<name>msubst</name>
<arg>
<funapp>
<name>msubst</name>
<arg>
<var>a</var>
</arg>
<arg>
<var>s</var>
</arg>
</funapp>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</lhs>
<rhs>
<funapp>
<name>msubst</name>
<arg>
<var>a</var>
</arg>
<arg>
<funapp>
<name>circ</name>
<arg>
<var>s</var>
</arg>
<arg>
<var>t</var>
</arg>
</funapp>
</arg>
</funapp>
</rhs>
</rule>
</rules>
<signature>
<funcsym>
<name>circ</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>cons</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>msubst</name>
<arity>2</arity>
</funcsym>
<funcsym>
<name>lift</name>
<arity>0</arity>
</funcsym>
<funcsym>
<name>id</name>
<arity>0</arity>
</funcsym>
<funcsym>
<name>subst</name>
<arity>2</arity>
</funcsym>
</signature>
</trs>
<strategy>INNERMOST</strategy>
<startterm>
<constructor-based/>
</startterm>
<metainformation>
<originalfilename>./TRS/secret05/cime2.trs</originalfilename>
</metainformation>
</problem>
